### ISSUE TITLE
Visualization FNF not working

### ISSUE THREAD

**Issue by lecrabe** [lecrabe/alos_mosaics#10]
The selection of FNF in the visualization TAB still brings the backscatter image

**Comment by 12rambau** [comment]
@lecrabe is this issue related to #9 ?

 if you set the year post 2017 and try to display the FNF, then the visualization is simply not displayed as there is no dataset. The code will thus fallback to the last method selected.

If it's not I'm unable to reproduce your issue

**Comment by 12rambau** [comment]
solved in #9
